version: '2'

services:
  dojo2-workspace-node:
    image: dojo2-workspace-node:8.12.0
    build: ./
    ports:
      - 3000:3000
      - 3001:3001
      - 8000:8000
    volumes:
      - ./../../:/workspace
    command: tail -f /dev/null